# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 1433:1433
    secrets:
      - db_password

  server:
    image: server
    build:
      context: .
      dockerfile: ./Server/Dockerfile
    environment:
      ConnectionStringsComics:
      ASPNETCORE_URLS: https://+/;http://+
      ASPNETCORE_KestrelCertificatesDefaultPath: /https/aspnetapp.pfx
      ASPNETCORE_KestrelCertificatesDefaultPassword: localhost
    ports:
      - 5178:80
      - 7038:443
    depends_on:
      - db
    secrets:
      - source: connection_string
        target: ConnectionStringsComics
    volumes:
      - '../../../../.aspnet/https:/https/'

secrets:
  db_password:
    file: ./.local/db_password.txt
  connection_string:
    file: ./.local/connection_string.txt