version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 1433:1433
    secrets:
      - db_password

  server:
    image: server
    build:
      context: .
      dockerfile: ./Server/Dockerfile
    environment:
      ConnectionStringsComics:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+/;http://+
      ASPNETCORE_KestrelCertificatesDefaultPath: /https/aspnetapp.pfx
      ASPNETCORE_KestrelCertificatesDefaultPassword: localhost
    ports:
      - 5077:80
      - 7207:443
    depends_on:
      - db
    secrets:
      - source: connection_string
        target: ConnectionStringsComics
    volumes:
      - '../../../../.aspnet/https:/https/'
      - ~/.vsdbg:/remote_debugger:rw

secrets:
  db_password:
    file: ./.local/db_password.txt
  connection_string:
    file: ./.local/connection_string.txt